[build]
  publish = "out"
  command = "npm run build"

# Catch-all for client-side routing - handle Next.js routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings for Next.js static export
[build.environment]
  NODE_VERSION = "18" 